# Whoper
# This file defines two services and a load balancer proxy, the db service and API service
version: '3'
services:
  postgres:
    build: ./SQL
    environment:
      POSTGRES_USER: whoperadmin
      POSTGRES_DB: whoperdb
      POSTGRES_PASSWORD: montanoarango
    volumes:
      - db-whoper:/var/lib/postgresql/data
    restart: always
    networks:
      whoper:
    ports:
      - "5432:5432"

  users:
    build: ./API/UsersService
    restart: always
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    networks:
      whoper:
    ports:
      - "3001:3001"
    volumes:
      - ./API/UsersService/bin/UsersAPI-linux:/bin/UsersAPI-linux

  posts:
    build: ./API/PostsService
    restart: always
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    networks:
      whoper:
    ports:
      - "3002:3002"
    volumes:
      - ./API/PostsService/bin/PostsAPI-linux:/bin/PostsAPI-linux

  ntwrs:
    build: ./API/NetworkService
    restart: always
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    networks:
      whoper:
    ports:
      - "3003:3003"
    volumes:
      - ./API/NetworkService/bin/NetworkAPI-linux:/bin/NetworkAPI-linux

  images:
    build: ./API/ImagesService
    restart: always
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    networks:
      whoper:
    ports:
      - "3004:3004"
    volumes:
      - ./API/ImagesService/bin/ImagesAPI-linux:/bin/ImagesAPI-linux

  auth:
    build: ./API/AuthService
    restart: always
    depends_on:
      - postgres
    networks:
      whoper:
    ports:
      - "5031:5001"
    volumes:
      - ./API/AuthService/bin/AuthServer-linux:/bin/AuthServer-linux

networks:
  whoper:

volumes:
  db-whoper:
# EOF!
